Created test to check Administration panel menu
IT-Academy-Social-Projects-KRV/EASYREST_Java_Sf pull request #10
Opened 2023-01-16 22:16 UTC by dashov

2023-01-17 07:36 UTC, TurgayArif requested changes
Empty class. Nothing to review. Please add some code.

2023-01-19 07:30 UTC, TurgayArif requested changes

2023-01-19 07:30 UTC, TurgayArif commented on src/test/java/com/easyrestaurant/tests/AdministratorPanel.java
> +        driver.findElement(By.xpath("//*[@id=\"root\"]/main/div/header/div/div[2]/div[2]/div/button[4]/span[1]/span/span")).isDisplayed();
Please add some assert method in this line.

2023-01-19 13:59 UTC, TurgayArif approved these changes

2023-01-21 12:51 UTC, balantaim approved these changes

2023-01-22 12:42 UTC, merged