Id 15 administrator restaurants list
IT-Academy-Social-Projects-KRV/EASYREST_Java_Sf pull request #5
Opened 2023-01-16 20:06 UTC by dashov

2023-01-17 07:07 UTC, TurgayArif requested changes

2023-01-17 07:07 UTC, TurgayArif commented on src/test/java/com/easyrestaurant/tests/AdministratorRestaurantsList.java
> +        driver.findElement(By.cssSelector("[href=\"/?tag=pizza\"]")).isDisplayed();
Please add an assertion to this line, because at the moment it just return true (if the element is found) and do nothing with it.

2023-01-17 07:07 UTC, TurgayArif commented on src/test/java/com/easyrestaurant/tests/AdministratorRestaurantsList.java
> +
Please add driver.quit();, because at the moment when the test is finished the webdriver stays opened.

2023-01-18 20:14 UTC, desislavavelichkova commented
Add some assert method.

2023-01-19 13:56 UTC, TurgayArif approved these changes

2023-01-19 20:23 UTC, desislavavelichkova approved these changes
Everything looks fine.

2023-01-21 12:46 UTC, balantaim approved these changes
You could declare only "Webdriver driver;" as global var. and in @BeforeClass could write driver = new ChromeDriver()

2023-01-22 12:58 UTC, merged